### ISSUE TITLE
Error on installing package

### ISSUE THREAD

**Issue by dariustsafack** [Yproximite/payum-axepta-bnp#4]
Hi,
Hope your are doing well.

I'm trying to install your package but I have got this below error message:

`[InvalidArgumentException]
  Could not find a matching version of package yproximite/payum-axepta-bnp. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stab
  ility (stable).`

I'm using:

- Composer v1
- OS : Windows 10

**Comment by RomulusED69** [comment]
Sorry for the late response
Package is now available in packagist
